import type { Metadata } from 'next';
import { Providers } from './Providers';
import localFont from 'next/font/local';
import './globals.css';

const cafe24Supermagic = localFont({
  src: [
    {
      path: '../../public/fonts/Cafe24Supermagic-Regular-v1.0.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Cafe24Supermagic-Bold-v1.0.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-cafe24-supermagic',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className={`${cafe24Supermagic.variable}`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
